import React from 'react';
import { Link } from 'react-router-dom';

/**
 * AboutPage component - About page for the Aniway application
 * Displays information about the project, features, team, and technologies
 */
const AboutPage = () => {
  return (
    <div className="bg-gradient-to-b from-green-50 to-white">
      {/* Hero Section */}
      <div className="relative bg-gray-800 text-white">
        <div className="container mx-auto px-6 py-20 relative z-10">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">About AniWay</h1>
          <p className="text-xl md:text-2xl max-w-3xl">
            Explore, stay and find your way! 
            Turning anime fan dreams into real-world adventures.
          </p>
        </div>
      </div>

      {/* Mission Section */}
      <div className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 mb-8 text-center">Our Mission</h2>
          <div className="bg-white rounded-lg shadow-lg p-8 mb-12 border-l-4 border-orange-400">
            <p className="text-lg text-gray-700 mb-6">
              Ever wanted to visit a place and act like an animated character in real life? Many anime fans dream of visiting real-world locations in their favorite series. However, the lack of reliable information makes trip planning challenging.
            </p>
            <p className="text-lg text-gray-700">
              AniWay bridges this gap by providing an AI-powered, anime-themed intelligent travel planner that simplifies the process and helps fans turn their anime journey into reality.
            </p>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="bg-green-50 py-16">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold text-gray-800 mb-12 text-center">Core Features</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow border-t-4 border-green-500">
              <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">Anime Location Discovery</h3>
              <p className="text-gray-600">
                Explore real-world locations featured in your favorite anime series with interactive maps and detailed information.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow border-t-4 border-orange-400">
              <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-orange-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">AI-Powered Itineraries</h3>
              <p className="text-gray-600">
                Get personalized travel plans generated by AI that include pricing, booking information, and anime-themed activity suggestions.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow border-t-4 border-gray-800">
              <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">Interactive Maps</h3>
              <p className="text-gray-600">
                Visualize your journey with detailed maps that highlight anime locations and optimize your routes for the best experience.
              </p>
            </div>

            {/* Feature 4 */}
            <div className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow border-t-4 border-green-500">
              <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">Trip Planning</h3>
              <p className="text-gray-600">
                Create, save, and share your anime-inspired itineraries with friends, complete with day-by-day schedules.
              </p>
            </div>
          </div>
        </div>
      </div>


      {/* Team Section */}
      <div className="bg-orange-50 py-16">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold text-gray-800 mb-12 text-center">Meet Team Rocket Webmasters</h2>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Team Member 1 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-gray-800">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Rocky Shi</h3>
                <p className="text-sm text-orange-400 mb-4">Tech Lead</p>
                <p className="text-gray-600">
                  Responsible for technical direction, code reviews, and resolving integration challenges.
                </p>
              </div>
            </div>
            
            {/* Team Member 2 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-green-500">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Hong Ying Xie</h3>
                <p className="text-sm text-orange-400 mb-4">Frontend Developer</p>
                <p className="text-gray-600">
                  Focused on creating responsive and intuitive user interfaces with React.
                </p>
              </div>
            </div>
            
            {/* Team Member 3 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-orange-400">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Nicholas Travis</h3>
                <p className="text-sm text-orange-400 mb-4">Backend Developer</p>
                <p className="text-gray-600">
                  Specializes in API development and database management.
                </p>
              </div>
            </div>
            
            {/* Team Member 4 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-gray-800">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Tun-Yu Hsieh</h3>
                <p className="text-sm text-orange-400 mb-4">Database Administrator</p>
                <p className="text-gray-600">
                  Manages MongoDB architecture and ensures data integrity.
                </p>
              </div>
            </div>
            
            {/* Team Member 5 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-green-500">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Yan Wa Ho</h3>
                <p className="text-sm text-orange-400 mb-4">UX/UI Designer</p>
                <p className="text-gray-600">
                  Creates engaging user experiences and anime-themed interface designs.
                </p>
              </div>
            </div>
            
            {/* Team Member 6 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow border-b-4 border-orange-400">
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-800 mb-1">Zephyr Chen</h3>
                <p className="text-sm text-orange-400 mb-4">Project Manager</p>
                <p className="text-gray-600">
                  Oversees project planning, risk management, and team coordination.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Technologies */}
      <div className="container mx-auto px-6 py-16">
        <h2 className="text-3xl font-bold text-gray-800 mb-12 text-center">Our Technology Stack</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          {/* Frontend */}
          <div className="bg-white rounded-lg shadow-md p-6 border-t-4 border-green-500">
            <h3 className="text-xl font-bold text-gray-800 mb-4">Frontend</h3>
            <ul className="space-y-2">
              <li className="flex items-center">
                <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                <span className="text-gray-700">React 19</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                <span className="text-gray-700">Redux</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                <span className="text-gray-700">TailwindCSS</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                <span className="text-gray-700">Mapbox Integration</span>
              </li>
            </ul>
          </div>
          
          {/* Backend */}
          <div className="bg-white rounded-lg shadow-md p-6 border-t-4 border-orange-400">
            <h3 className="text-xl font-bold text-gray-800 mb-4">Backend</h3>
            <ul className="space-y-2">
              <li className="flex items-center">
                <span className="w-2 h-2 bg-orange-400 rounded-full mr-2"></span>
                <span className="text-gray-700">Node.js</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-orange-400 rounded-full mr-2"></span>
                <span className="text-gray-700">Express.js</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-orange-400 rounded-full mr-2"></span>
                <span className="text-gray-700">MongoDB</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-orange-400 rounded-full mr-2"></span>
                <span className="text-gray-700">OpenAI API</span>
              </li>
            </ul>
          </div>
          
          {/* External APIs */}
          <div className="bg-white rounded-lg shadow-md p-6 border-t-4 border-gray-800">
            <h3 className="text-xl font-bold text-gray-800 mb-4">External APIs</h3>
            <ul className="space-y-2">
              <li className="flex items-center">
                <span className="w-2 h-2 bg-gray-800 rounded-full mr-2"></span>
                <span className="text-gray-700">Google Places API</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-gray-800 rounded-full mr-2"></span>
                <span className="text-gray-700">Mapbox API</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-gray-800 rounded-full mr-2"></span>
                <span className="text-gray-700">Anitabi API</span>
              </li>
              <li className="flex items-center">
                <span className="w-2 h-2 bg-gray-800 rounded-full mr-2"></span>
                <span className="text-gray-700">OpenAI API</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-gray-800 text-white py-16">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-6">Ready to Begin Your Anime Adventure?</h2>
          <p className="text-xl max-w-2xl mx-auto mb-8">
            Start planning your anime-inspired journey today and experience the magic of your favorite series in real life.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to="/" className="bg-orange-400 text-white hover:bg-orange-500 font-bold py-3 px-8 rounded-lg transition-colors inline-block shadow-md hover:shadow-lg">
              Get Started
            </Link>
            <Link to="/reference" className="bg-transparent border-2 border-green-500 hover:bg-green-500 hover:text-white font-bold py-3 px-8 rounded-lg transition-colors inline-block">
              Learn More
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;